language: node_js
node_js:
  - "4.2.1"
os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

services:
  - mongodb
  - redis

before_install:
  - export CC="gcc-4.9" CXX="g++-4.9"
before_script:
  - npm install
  - npm install -g gulp
  - npm install -g bower
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 1 # give server time to start

script:
  - npm test
