language: node_js
node_js:
  - "4.2.1"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9


before_script:
  - export DISPLAY=:99.0
  - export CC="gcc-4.9" CXX="g++-4.9"
  - sh -e /etc/init.d/xvfb start
  - sleep 1 # give server time to start

script:
  - npm test
